# Generated by Django 4.2.9 on 2024-02-19 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("journey", "0001_initial"),
        ("common", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userchallenges",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_challenges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userchallengerecommendationtype",
            name="recommendation_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendation_types",
                to="journey.recommendationtype",
            ),
        ),
        migrations.AddField(
            model_name="userchallengerecommendationtype",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_challenge_recommendation_types",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userchallengerecommendationtype",
            name="user_challenge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenge_recommendation_types",
                to="journey.userchallenges",
            ),
        ),
        migrations.AddField(
            model_name="quests",
            name="challenge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quests",
                to="journey.challenges",
            ),
        ),
        migrations.AddField(
            model_name="quests",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_quests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="questrequests",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quests_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="powerups",
            name="quest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="powerups",
                to="journey.quests",
            ),
        ),
        migrations.AddField(
            model_name="powerups",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_powerups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="obstacles",
            name="quest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="obstacles",
                to="journey.quests",
            ),
        ),
        migrations.AddField(
            model_name="obstacles",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_obstacles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="herotypes",
            name="role_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="role_hero",
                to="journey.roletype",
            ),
        ),
        migrations.AddField(
            model_name="challenges",
            name="age_group",
            field=models.ManyToManyField(
                related_name="age_group_challenges", to="common.agegroup"
            ),
        ),
        migrations.AddField(
            model_name="challenges",
            name="ethnicity",
            field=models.ManyToManyField(
                related_name="ethnicity_challenges", to="common.ethnicity"
            ),
        ),
        migrations.AddField(
            model_name="challengerequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenge_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
