# Generated by Django 4.2.9 on 2024-02-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_initial"),
        ("journey", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenges",
            name="age_group",
            field=models.ManyToManyField(
                blank=True, related_name="age_group_challenges", to="common.agegroup"
            ),
        ),
        migrations.AlterField(
            model_name="challenges",
            name="ethnicity",
            field=models.ManyToManyField(
                blank=True, related_name="ethnicity_challenges", to="common.ethnicity"
            ),
        ),
    ]
