# Generated by Django 4.2.9 on 2024-03-08 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
        ('discovery', '0001_initial'),
        ('journey', '0003_alter_challenges_age_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyMedia',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('media_type', models.CharField(choices=[('book', 'Book'), ('video', 'Video'), ('audio', 'Audio'), ('website', 'Website'), ('game', 'Game'), ('activity', 'Activity')], max_length=10)),
                ('title', models.CharField(max_length=250)),
                ('link', models.TextField()),
                ('image', models.ImageField(upload_to='media_journey/')),
            ],
            options={
                'verbose_name': 'Journey Media',
                'verbose_name_plural': 'Journey Media',
            },
            bases=('common.basemodel',),
        ),
        migrations.CreateModel(
            name='OutcomeItems',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Outcome Items',
                'verbose_name_plural': 'Outcome Items',
            },
            bases=('common.basemodel',),
        ),
        migrations.CreateModel(
            name='QuestTraits',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('virtue', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Quest Traits',
                'verbose_name_plural': 'Quest Traits',
            },
            bases=('common.basemodel',),
        ),
        migrations.CreateModel(
            name='QuestTypes',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('label', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Quest Types',
                'verbose_name_plural': 'Quest Types',
            },
            bases=('common.basemodel',),
        ),
        migrations.RemoveField(
            model_name='obstacles',
            name='name',
        ),
        migrations.RemoveField(
            model_name='powerups',
            name='name',
        ),
        migrations.AddField(
            model_name='challenges',
            name='card_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='quests',
            name='adult_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quests',
            name='age_group',
            field=models.ManyToManyField(blank=True, related_name='age_group_quests', to='common.agegroup'),
        ),
        migrations.AddField(
            model_name='quests',
            name='desired_outcome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quests',
            name='items_required',
            field=models.ManyToManyField(blank=True, related_name='quest_items_required', to='discovery.items'),
        ),
        migrations.AddField(
            model_name='quests',
            name='success_rule',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='obstacles',
            name='label',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='obstacles',
            name='threat_type',
            field=models.CharField(choices=[('trap', 'Trap'), ('trigger', 'Trigger'), ('symptom', 'Symptom'), ('mental_block', 'Mental Block')], max_length=20),
        ),
        migrations.AlterField(
            model_name='powerups',
            name='label',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='powerups',
            name='powerup_type',
            field=models.CharField(choices=[('tool', 'Tool'), ('trait', 'Trait'), ('ally', 'Ally')], max_length=20),
        ),
        migrations.AddField(
            model_name='quests',
            name='items_to_be_used',
            field=models.ManyToManyField(blank=True, to='journey.outcomeitems'),
        ),
        migrations.AddField(
            model_name='quests',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='journey_media_quests', to='journey.journeymedia'),
        ),
        migrations.AddField(
            model_name='quests',
            name='traits',
            field=models.ManyToManyField(blank=True, related_name='quest_traits', to='journey.questtraits'),
        ),
        migrations.AddField(
            model_name='quests',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='quest_types', to='journey.questtypes'),
        ),
    ]
