# Generated by Django 4.2.9 on 2024-03-12 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0004_journeymedia_outcomeitems_questtraits_questtypes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questrequests',
            name='user_challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_quest_requests', to='journey.userchallenges'),
        ),
    ]
