# Generated by Django 4.2.9 on 2024-03-16 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
        ('journey', '0005_questrequests_user_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengerequest',
            name='is_request_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challengerequest',
            name='request_status',
            field=models.CharField(choices=[('Added', 'Added'), ('Existed', 'Already Exist'), ('Discard', 'Discarded'), ('Pending', 'Pending')], default='Pending'),
        ),
        migrations.AddField(
            model_name='questrequests',
            name='is_request_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questrequests',
            name='request_status',
            field=models.CharField(choices=[('Added', 'Added'), ('Existed', 'Already Exist'), ('Discard', 'Discarded'), ('Pending', 'Pending')], default='Pending'),
        ),
        migrations.CreateModel(
            name='UserChallengeQuests',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('is_completed', models.BooleanField(default=False)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_challenge_quests', to='journey.quests')),
                ('user_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_challenge_quests', to='journey.userchallenges')),
            ],
            options={
                'verbose_name': 'User-Challenge Quests',
                'verbose_name_plural': 'User-Challenge Quests',
                'unique_together': {('user_challenge', 'quest')},
            },
            bases=('common.basemodel',),
        ),
    ]
