# Generated by Django 4.2.9 on 2024-03-17 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
        ('journey', '0006_challengerequest_is_request_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallengequests',
            name='quest_start_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='UserChallengeQuestPowerups',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('powerup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chellange_powerup', to='journey.powerups')),
                ('user_challenge_quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chellange_quest_powerup', to='journey.userchallengequests')),
            ],
            options={
                'verbose_name': 'User-Challenge-Quests Powerups',
                'verbose_name_plural': 'User-Challenge-Quests Powerups',
                'unique_together': {('user_challenge_quest', 'powerup')},
            },
            bases=('common.basemodel',),
        ),
        migrations.CreateModel(
            name='UserChallengeQuestObstacles',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('obstacle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chellange_obstacles', to='journey.obstacles')),
                ('user_chellenge_quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chellange_quest_obstacles', to='journey.userchallengequests')),
            ],
            options={
                'verbose_name': 'User-Challenge-Quests Obstacles',
                'verbose_name_plural': 'User-Challenge-Quests Obstacles',
                'unique_together': {('user_chellenge_quest', 'obstacle')},
            },
            bases=('common.basemodel',),
        ),
    ]
