# Generated by Django 4.2.9 on 2024-03-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0007_userchallengequests_quest_start_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallengequestobstacles',
            name='obstacle_progress',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
