# Generated by Django 4.2.9 on 2024-03-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0008_userchallengequestobstacles_obstacle_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallengequestpowerups',
            name='powerup_progress',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
