# Generated by Django 4.2.9 on 2024-03-19 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0009_userchallengequestpowerups_powerup_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchallenges',
            name='hero_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hero_challenges', to='journey.herotypes'),
        ),
    ]
