# Generated by Django 4.2.9 on 2024-03-19 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journey', '0010_alter_userchallenges_hero_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allies',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('invite_code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('superpower', models.CharField(verbose_name=300)),
                ('relationship', models.CharField(verbose_name=250)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, related_name='allies', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ally', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Allies',
                'verbose_name_plural': 'Allies',
            },
            bases=('common.basemodel',),
        ),
        migrations.CreateModel(
            name='AlliesQuests',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('ally', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allies_quests', to='journey.allies')),
                ('user_quests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_allies', to='journey.userchallengequests')),
            ],
            options={
                'verbose_name': 'Allies Quests',
                'verbose_name_plural': 'Allies Quests',
            },
            bases=('common.basemodel',),
        ),
    ]
