# Generated by Django 4.2.9 on 2024-03-19 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journey', '0011_allies_alliesquests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allies',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allies', to=settings.AUTH_USER_MODEL),
        ),
    ]
