# Generated by Django 4.2.9 on 2024-03-21 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journey', '0012_alter_allies_invited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allies',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ally_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
