# Generated by Django 4.2.9 on 2024-04-04 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journey', '0014_allies_invite_sent_allies_invite_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allies',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='allies',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ally_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
