# Generated by Django 4.2.9 on 2024-03-16 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_initial"),
        ("discovery", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="identifier",
        ),
        migrations.CreateModel(
            name="MediaIdentifier",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.basemodel",
                    ),
                ),
                ("identifier", models.CharField(max_length=13, unique=True)),
                (
                    "discovery_media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_identifiers",
                        to="discovery.media",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Identifier",
                "verbose_name_plural": "Media Identifiers",
            },
            bases=("common.basemodel",),
        ),
    ]
