# Generated by Django 4.2.9 on 2024-03-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0002_remove_media_identifier_mediaidentifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="o_type",
            field=models.CharField(
                blank=True,
                choices=[("fiction", "Fiction"), ("non_fiction", "Non-Fiction")],
                max_length=50,
                null=True,
                verbose_name="Fiction or non-fiction?",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hardcover", "Hardcover"),
                    ("paperback", "Paperback"),
                    ("ebook", "Ebook"),
                    ("audiobook", "Audiobook"),
                    ("other", "Other"),
                    ("dvd", "DVD"),
                    ("bluray", "Blu-Ray"),
                    ("vhs", "Vhs"),
                    ("streaming", "Streaming"),
                    ("other", "Other"),
                    ("cd", "CD"),
                    ("vinyl", "Vinyl"),
                    ("cassette", "Cassette"),
                    ("streaming", "Streaming"),
                    ("other", "Other"),
                    ("podcast", "Podcast"),
                    ("audiobook", "Audiobook"),
                    ("other", "Other"),
                    ("video_game", "Video Game"),
                    ("board_game", "Board Game"),
                    ("mobile_game", "Mobile Game"),
                    ("tabletop_game", "Tabletop RPG"),
                    ("other", "Other"),
                    ("live_performance", "Live Performance"),
                    ("recording", "Recording"),
                    ("other", "Other"),
                    ("sculpture", "Sculpture"),
                    ("painting", "Painting"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
