# Generated by Django 4.2.9 on 2024-03-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0003_media_o_type_alter_media_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="summary_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="o_type",
            field=models.CharField(
                blank=True,
                choices=[("fiction", "Fiction"), ("non_fiction", "Non-Fiction")],
                max_length=50,
                null=True,
                verbose_name="Fiction or Non-fiction?",
            ),
        ),
    ]
