# Generated by Django 4.2.9 on 2024-03-17 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_initial"),
        ("discovery", "0004_media_summary_link_alter_media_o_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddtionalResource",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.basemodel",
                    ),
                ),
                ("link", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "discovery_media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_addtional_resources",
                        to="discovery.media",
                    ),
                ),
            ],
            options={
                "verbose_name": "Addtional Resource",
                "verbose_name_plural": "Addtional Resources",
            },
            bases=("common.basemodel",),
        ),
    ]
