# Generated by Django 4.2.9 on 2024-03-17 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_initial"),
        ("discovery", "0005_addtionalresource"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalResource",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.basemodel",
                    ),
                ),
                ("link", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Additional Resource",
                "verbose_name_plural": "Additional Resources",
            },
            bases=("common.basemodel",),
        ),
        migrations.AddField(
            model_name="mediacredits",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="discovery/media/credits/"
            ),
        ),
        migrations.AddField(
            model_name="mediacredits",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediacredits",
            name="summary_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="AddtionalResource",
        ),
        migrations.AddField(
            model_name="additionalresource",
            name="discovery_media",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_additional_resources",
                to="discovery.media",
            ),
        ),
    ]
