# Generated by Django 4.2.9 on 2024-03-17 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0006_additionalresource_mediacredits_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionalresource",
            name="media_credit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_resources",
                to="discovery.mediacredits",
            ),
        ),
        migrations.AlterField(
            model_name="additionalresource",
            name="discovery_media",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_resources",
                to="discovery.media",
            ),
        ),
    ]
