# Generated by Django 4.2.9 on 2024-03-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0008_alter_additionalresource_discovery_media"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediacredits",
            name="discovery_media",
        ),
        migrations.AddField(
            model_name="media",
            name="media_credits",
            field=models.ManyToManyField(
                blank=True,
                related_name="media_credits",
                related_query_name="media_credit",
                to="discovery.mediacredits",
            ),
        ),
    ]
