# Generated by Django 4.2.9 on 2024-03-17 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0011_reviews_quotes"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionalresource",
            name="character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_resources",
                to="discovery.characters",
            ),
        ),
        migrations.AddField(
            model_name="characters",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="characters",
            name="o_type",
            field=models.CharField(
                blank=True,
                choices=[("fiction", "Fiction"), ("real", "Real")],
                max_length=50,
                null=True,
                verbose_name="Is this character real or fictional?",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="o_type",
            field=models.CharField(
                blank=True,
                choices=[("fiction", "Fiction"), ("real", "Real")],
                max_length=50,
                null=True,
                verbose_name="Fiction or Non-fiction?",
            ),
        ),
        migrations.AlterField(
            model_name="places",
            name="place_type",
            field=models.CharField(
                blank=True,
                choices=[("fiction", "Fiction"), ("real", "Real")],
                max_length=100,
                null=True,
                verbose_name="Is this place real or fictional?",
            ),
        ),
        migrations.AlterField(
            model_name="places",
            name="source_type",
            field=models.CharField(
                blank=True,
                choices=[("native", "Native"), ("mentioned", "Mentioned")],
                max_length=50,
                null=True,
                verbose_name="Is this place mentioned in this media or native to this media?",
            ),
        ),
    ]
