# Generated by Django 4.2.9 on 2024-03-17 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0013_additionalresource_place_places_lat_places_link_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="places",
            old_name="place_type",
            new_name="o_type",
        ),
        migrations.AddField(
            model_name="additionalresource",
            name="genre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_resources",
                to="discovery.genres",
            ),
        ),
        migrations.AddField(
            model_name="additionalresource",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_resources",
                to="discovery.themes",
            ),
        ),
        migrations.AddField(
            model_name="additionalresource",
            name="time_period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_resources",
                to="discovery.timeperiods",
            ),
        ),
        migrations.AddField(
            model_name="additionalresource",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_resources",
                to="discovery.topics",
            ),
        ),
        migrations.AddField(
            model_name="items",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="items",
            name="o_type",
            field=models.CharField(
                blank=True,
                choices=[("fiction", "Fiction"), ("real", "Real")],
                max_length=50,
                null=True,
                verbose_name="Is this item real or fictional?",
            ),
        ),
    ]
