# Generated by Django 4.2.9 on 2024-03-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0015_additionalresource_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genres",
            name="source_type",
            field=models.CharField(
                blank=True,
                choices=[("native", "Native"), ("mentioned", "Mentioned")],
                max_length=50,
                null=True,
                verbose_name="Is this genre mentioned in this media or native to this media?",
            ),
        ),
        migrations.AlterField(
            model_name="items",
            name="source_type",
            field=models.CharField(
                blank=True,
                choices=[("native", "Native"), ("mentioned", "Mentioned")],
                max_length=50,
                null=True,
                verbose_name="Is this item mentioned in this media or native to this media?",
            ),
        ),
        migrations.AlterField(
            model_name="timeperiods",
            name="source_type",
            field=models.CharField(
                blank=True,
                choices=[("native", "Native"), ("mentioned", "Mentioned")],
                max_length=50,
                null=True,
                verbose_name="Is this time period mentioned in this media or native to this media?",
            ),
        ),
        migrations.AlterField(
            model_name="topics",
            name="source_type",
            field=models.CharField(
                blank=True,
                choices=[("native", "Native"), ("mentioned", "Mentioned")],
                max_length=50,
                null=True,
                verbose_name="Is this topic mentioned in this media or native to this media?",
            ),
        ),
    ]
