# Generated by Django 4.2.9 on 2024-03-17 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0016_alter_genres_source_type_alter_items_source_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionalresource",
            name="career",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_resources",
                to="discovery.careerinterests",
            ),
        ),
        migrations.AddField(
            model_name="careerinterests",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
