# Generated by Django 4.2.9 on 2024-04-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0018_groupcategory_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="characters",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="character_groups",
                to="discovery.groups",
            ),
        ),
        migrations.AddField(
            model_name="items",
            name="groups",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="item_groups", to="discovery.groups"
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="media_groups", to="discovery.groups"
            ),
        ),
        migrations.AddField(
            model_name="places",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="place_groups",
                to="discovery.groups",
            ),
        ),
    ]
