# Generated by Django 4.2.9 on 2024-04-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0019_characters_groups_items_groups_media_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactertraits",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="charactertraits",
            name="mongo_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
