# Generated by Django 4.2.9 on 2024-04-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0022_items_active_items_mongo_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="places",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="places",
            name="mongo_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
