# Generated by Django 4.2.9 on 2024-04-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0024_purchaseoppurtunities_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseoppurtunities",
            name="link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseoppurtunities",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
