# Generated by Django 4.2.9 on 2024-04-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0025_alter_purchaseoppurtunities_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="themes",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="themes",
            name="mongo_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
