# Generated by Django 4.2.9 on 2024-04-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0031_characters_active_characters_mongo_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="media",
            old_name="is_active",
            new_name="active",
        ),
        migrations.AddField(
            model_name="media",
            name="mongo_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
