# Generated by Django 4.2.9 on 2024-04-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0032_rename_is_active_media_active_media_mongo_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="stub",
            field=models.BooleanField(default=False),
        ),
    ]
