# Generated by Django 4.2.9 on 2024-04-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0033_media_stub"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
