# Generated by Django 4.2.9 on 2024-04-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0034_alter_media_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="title",
            field=models.CharField(max_length=500),
        ),
    ]
