# Generated by Django 4.2.9 on 2024-04-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0035_alter_media_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalresource",
            name="link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="careerinterests",
            name="link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="characters",
            name="link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="items",
            name="link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="summary_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="mediacredits",
            name="summary_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="places",
            name="link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
