# Generated by Django 4.2.9 on 2024-04-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0036_alter_additionalresource_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaidentifier",
            name="identifier",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
