# Generated by Django 4.2.9 on 2024-04-09 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_initial"),
        ("discovery", "0037_alter_mediaidentifier_identifier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="characters",
            name="source_type",
        ),
        migrations.RemoveField(
            model_name="media",
            name="characters",
        ),
        migrations.RemoveField(
            model_name="media",
            name="media_credits",
        ),
        migrations.RemoveField(
            model_name="places",
            name="source_type",
        ),
        migrations.CreateModel(
            name="MediaPlace",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.basemodel",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        choices=[("native", "Native"), ("mentioned", "Mentioned")],
                        max_length=50,
                        null=True,
                        verbose_name="Is this place mentioned in this media or native to this media?",
                    ),
                ),
                (
                    "discovery_media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discovery.media",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discovery.places",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Place",
                "verbose_name_plural": "Media Places",
            },
            bases=("common.basemodel",),
        ),
        migrations.CreateModel(
            name="MediaCreditsReference",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.basemodel",
                    ),
                ),
                (
                    "discovery_media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_credits",
                        to="discovery.media",
                    ),
                ),
                (
                    "media_credit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_credits",
                        to="discovery.mediacredits",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Credits Reference",
                "verbose_name_plural": "Media Credits References",
            },
            bases=("common.basemodel",),
        ),
        migrations.CreateModel(
            name="MediaCharacter",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.basemodel",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        choices=[("native", "Native"), ("mentioned", "Mentioned")],
                        max_length=50,
                        null=True,
                        verbose_name="Is this character mentioned in this media or native to this media?",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_characters",
                        to="discovery.characters",
                    ),
                ),
                (
                    "discovery_media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_characters",
                        to="discovery.media",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Character",
                "verbose_name_plural": "Media Characters",
            },
            bases=("common.basemodel",),
        ),
    ]
