# Generated by Django 4.2.9 on 2024-04-09 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0038_remove_characters_source_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="places",
        ),
        migrations.AlterField(
            model_name="mediaplace",
            name="discovery_media",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_places",
                to="discovery.media",
            ),
        ),
        migrations.AlterField(
            model_name="mediaplace",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_places",
                to="discovery.places",
            ),
        ),
    ]
