# Generated by Django 4.2.9 on 2024-04-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0042_remove_media_can_lend_remove_media_progress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="characters",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="charactertraits",
            name="label",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="charactertraits",
            name="mongo_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="genres",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="groupcategory",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="groups",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="items",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="mediacredits",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="mediaidentifier",
            name="identifier",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="places",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="quotes",
            name="location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="quotes",
            name="said_by",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="themes",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="timeperiods",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="topics",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
